# Generated by Django 4.2.1 on 2023-05-27 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Product ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('description', models.TextField(max_length=500, verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='customer_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Customer ID'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Order ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Date Ordered')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Purchased', 'Purchased'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50, verbose_name='Status')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('product_ordered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Product Ordered')),
            ],
        ),
    ]
