# Generated by Django 4.2.1 on 2023-05-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_alter_customuser_customer_id_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.UUIDField>', verbose_name='Product Image'),
        ),
    ]
