# Generated by Django 4.2.1 on 2023-05-29 23:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_upload_to, verbose_name='Product Image'),
        ),
    ]
